// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rppesdahniuwawcnernm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwcGVzZGFobml1d2F3Y25lcm5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzM3OTYsImV4cCI6MjA3MjcwOTc5Nn0.zUZdB7o85nZ58R8t3sp1SMGAEdMsh5U70PKxPpvDuGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});